[project]
name = "ros2-onnxcomp"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "onnx>=1.19.1",
    "onnxruntime-gpu>=1.23.2",
    "opencv-python>=4.12.0.88",
    "pyyaml>=6.0.3",
]
